- name: "Extract artifact"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/
    remote_src:  no

- name: Copy .env
  copy:
    src: .env
    dest: /home/ubuntu/

- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Enable pm2
  become: true
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"

- name: "Run backend app"
  become: true
  args:
    chdir: /home/ubuntu/dist
  shell: |
    pm2 start main.js
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"


#
#
#- copy:
#    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
#    dest: /home/ubuntu/backend
#
#- name: Extract artifact.tar.gz to EC2
#  unarchive:
#    src: artifact.tar.gz
#    dest: /home/ubuntu/backend


